# Generated by Django 5.1.4 on 2025-01-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='EarringDetail',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.product')),
                ('material', models.CharField(max_length=100)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Earring Details',
                'db_table': 'earring_details',
            },
        ),
        migrations.CreateModel(
            name='ShoeDetail',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.product')),
                ('color', models.CharField(max_length=50)),
                ('materials', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Shoe Details',
                'db_table': 'shoe_details',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.product')),
                ('sale', models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.sale')),
            ],
            options={
                'verbose_name_plural': 'Sale Items',
                'db_table': 'sale_items',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.region')),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='ShoeStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.store')),
            ],
            options={
                'verbose_name_plural': 'Shoe Stock',
                'db_table': 'shoe_stock',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.store'),
        ),
        migrations.CreateModel(
            name='EarringStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.store')),
            ],
            options={
                'verbose_name_plural': 'Earring Stock',
                'db_table': 'earring_stock',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.tag')),
            ],
            options={
                'verbose_name_plural': 'Product Tags',
                'db_table': 'product_tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.role')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.user'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.user'),
        ),
        migrations.AddField(
            model_name='region',
            name='regional_manager',
            field=models.ForeignKey(blank=True, db_column='regional_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.user'),
        ),
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.store')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
            options={
                'verbose_name_plural': 'User Stores',
                'db_table': 'user_stores',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='idx_categories_parent_id'),
        ),
        migrations.AddIndex(
            model_name='earringdetail',
            index=models.Index(fields=['material'], name='idx_earring_details_material'),
        ),
        migrations.AddIndex(
            model_name='shoedetail',
            index=models.Index(fields=['color'], name='idx_shoe_details_color'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_products_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_products_category_id'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='idx_products_created_at'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='idx_sale_items_sale_id'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='idx_sale_items_product_id'),
        ),
        migrations.AddIndex(
            model_name='shoestock',
            index=models.Index(fields=['product'], name='idx_shoe_stock_product_id'),
        ),
        migrations.AddIndex(
            model_name='shoestock',
            index=models.Index(fields=['store'], name='idx_shoe_stock_store_id'),
        ),
        migrations.AddIndex(
            model_name='shoestock',
            index=models.Index(fields=['size'], name='idx_shoe_stock_size'),
        ),
        migrations.AddIndex(
            model_name='shoestock',
            index=models.Index(fields=['store', 'product'], name='idx_shoe_stock_store_product'),
        ),
        migrations.AddConstraint(
            model_name='shoestock',
            constraint=models.UniqueConstraint(fields=('product', 'store', 'size'), name='unique_shoe_stock'),
        ),
        migrations.AddIndex(
            model_name='earringstock',
            index=models.Index(fields=['product'], name='idx_earring_stock_product_id'),
        ),
        migrations.AddIndex(
            model_name='earringstock',
            index=models.Index(fields=['store'], name='idx_earring_stock_store_id'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['product'], name='idx_product_tags_product_id'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['tag'], name='idx_product_tags_tag_id'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role_id'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['region'], name='idx_stores_region_id'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['manager'], name='idx_stores_manager_id'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['user'], name='idx_sales_user_id'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store'], name='idx_sales_store_id'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['regional_manager'], name='idx_regional_manager_id'),
        ),
        migrations.AlterUniqueTogether(
            name='userstore',
            unique_together={('user', 'store')},
        ),
    ]
